name: CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches:   
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Install dependencies"
        run: npm install

      - name: "Build Image"
        run: |
            docker build -t oluwaseun7/dmailer:latest .

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Push Image to Docker Hub"
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/dmailer:latest
            docker run -p 3000:3000 -d ${{secrets.DOCKER_USERNAME}}/dmailer:latest
       


     