name: CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches:   
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Install dependencies"
        run: npm install

      - name: "Build Image"
        run: |
            docker build -t oluwaseun7/dmailer:latest .

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Push Image to Docker Hub"
        run: |
            docker push oluwaseun7/dmailer:latest
            docker run -p 3000:3000 -d oluwaseun7/dmailer:latest

     
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./path/to/artifact

      - name: Send email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: "GitHub Action Notification"
          body: "Hello! This is a test email sent from GitHub Actions."
          to: "theoafactr@gmail.com"
          from: ${{ secrets.EMAIL }}
          secure: true # Set to false for non-TLS/SSL connections
          tls: true
  
  Download:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact




     